import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background relative flex flex-col">
      <Navbar />
      <main className="flex-1 pt-28 pb-16 container mx-auto px-4 max-w-4xl">
        <h1 className="text-4xl md:text-5xl font-bold mb-6 text-gradient">Terms of Service</h1>
        <div className="space-y-6 text-muted-foreground text-sm leading-relaxed shadow-sm p-8 rounded-3xl glass-card">
          <p className="font-bold text-foreground">Last Updated: {new Date().toLocaleDateString()}</p>
          
          <h2 className="text-xl font-bold text-foreground mt-6 mb-2">1. Introduction</h2>
          <p>
            Welcome to FlowCapital. By accessing our platform, you agree to these Terms of Service. These terms govern your use of the FlowCapital marketplace, protocol, and any related autonomous factoring services provided by our smart contracts and APIs.
          </p>

          <h2 className="text-xl font-bold text-foreground mt-6 mb-2">2. Eligibility & Verification (KYB/KYC)</h2>
          <p>
            Users must complete appropriate "Know Your Business" (KYB) and anti-money laundering checks before participating as an SME, Enterprise, or Investor. Providing false information will result in immediate account termination.
          </p>

          <h2 className="text-xl font-bold text-foreground mt-6 mb-2">3. Role-Specific Obligations</h2>
          <ul className="list-inside list-disc space-y-2">
            <li><strong className="text-foreground">SMEs:</strong> Must only upload legitimate, undisputed commercial invoices. Fraudulent uploads are punishable by law.</li>
            <li><strong className="text-foreground">Enterprises:</strong> Must verify and irrevocably commit to paying the invoice total directly to the protocol settlement escrow on the due date.</li>
            <li><strong className="text-foreground">Investors:</strong> Acknowledge that while risks are assessed by AI, investing in trade finance carries inherent capital risk.</li>
          </ul>

          <h2 className="text-xl font-bold text-foreground mt-6 mb-2">4. Smart Contract Governance</h2>
          <p>
            Upon enterprise verified acceptance, the asset is tokenized. Yields and disbursements are managed programmatically. Once a contract is executed on-chain, it cannot be manually reversed.
          </p>

          <h2 className="text-xl font-bold text-foreground mt-6 mb-2">5. Disclaimer of Liability</h2>
          <p>
            FlowCapital provides the software and infrastructure but does not guarantee the financial performance of any specific invoice. Yields are generated by enterprise repayment, and defaults (though mitigated) remain a possibility.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
